development: &default
  host: 'http://localhost:9200/'
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  host: 'search-myelasticservice-7evfpsw7dhdsg6ddl37j5sx5ya.us-east-2.es.amazonaws.com', port: 80, log: true
  transport_options:
    request:
      timeout: !!integer 300

